seed: 42
learning_rate: 0.0001
num_steps: 60000
log_interval_steps: 50
checkpoint_interval_steps: 1000
device: cuda
checkpoint_dir: /projects/u6ga/sk3925_misc/checkpoints/pretrain
dataloader_config_path: dataset_processing/config/dataloader.yaml
num_expression_params: 50
