seed: 42
learning_rate: 0.0001
num_steps: 100000
log_interval_steps: 50
checkpoint_interval_steps: 1000
device: cuda
checkpoint_dir: /projects/u6kf/sk3925_misc/checkpoints/stage2
stage1_checkpoint_pth: /projects/u6kf/sk3925_misc/checkpoints/pretrain/step_00059999.pt
dataloader_config_path: dataset_processing/config/dataloader.yaml
pass_pattern: [A, B, C]
pass_b_alternation_period: 1
# checkpoint_pth: /projects/u6kf/sk3925_misc/checkpoints/stage2/step_00017999.pt
